module.exports={
   MONGOURL:"mongodb+srv://Yashav:mongodb@cluster0.qc0rq.mongodb.net/Project?retryWrites=true&w=majority"
}
//if(process.env.MODE==='production')
//{
//module.exports=require('./prod');
//}else
//{
//module.exports=require('./devs');
//}